### PR TITLE
Fix #157 flaky //third_party/beam:gbk_test

### LINKED ISSUE #157: Test failure: //third_party/beam:gbk_test
https://buildbot-dot-kythe-repo.appspot.com/#/builders/1/builds/3

```
--- FAIL: TestCombinePerKey (0.00s)
	gbk_test.go:92: panic: value 9 expected, but not present goroutine 8 [running]:
```

### PR DESCRIPTION
**Pull request by schroederc**
The passert package matches its input collections based on their
ordering which can be non-deterministic when the CoGBK implementation is
parallel.

### CODE REVIEW

**Comment by kythe** [comment]
[Buildbot bazel-kythe status](http://localhost:8010/#/builders/1/builds/9) for https://github.com/google/kythe/commit/13ed38361a0f7e88fa7a85e1fbf09b203a235d90: `build successful`

**Comment by kythe** [comment]
[Buildbot go-kythe status](http://localhost:8010/#/builders/1/builds/10) for https://github.com/google/kythe/commit/13ed38361a0f7e88fa7a85e1fbf09b203a235d90: `build successful`

File: third_party/beam/sdks/go/pkg/beam/runners/disksort/gbk_test.go [hunk 1]
```diff
@@ -22,13 +22,18 @@ import (
...
 
+// Disable parallelism to work with order-dependent passert checks.
+func init() { *gbkConcurrency = 1 }
+
 func TestGBK(t *testing.T) {
 	p, s, nums := ptest.CreateList([]int{1, 2, 3, 4, 2, 3, 3})
 
 	kv := beam.ParDo(s, extendToKey, nums)
 	sums := beam.DropKey(s, beam.ParDo(s, sum, beam.GroupByKey(s, kv)))
+	debug.Print(s, sums)
```
Comment (salguarnieri) [inline third_party/beam/sdks/go/pkg/beam/runners/disksort/gbk_test.go]: Is this leftover or useful?

Comment (schroederc) [reply third_party/beam/sdks/go/pkg/beam/runners/disksort/gbk_test.go]: They're useful since the `passert` package just panics on a failure.
