### PR TITLE
Fix KzipWriter to include mandatory directory entries and update test…

### LINKED ISSUE #3054: C++ kzip writer does not generate a root directory
Per http://www.kythe.io/docs/kythe-kzip.html, a kzip file is intended to have a directory as its first entry. The C++ writer emits the correct subdirectory structure, but does not include the root directory itself.

### PR DESCRIPTION
**Pull request by shahms**
…s to check/allow for this

Fixes #3054

### CODE REVIEW

File: kythe/cxx/common/kzip_writer.cc [hunk 1]
```diff
@@ -84,6 +97,14 @@ KzipWriter::~KzipWriter() {
 
 StatusOr<std::string> KzipWriter::WriteUnit(
     const kythe::proto::IndexedCompilation& unit) {
+  if (!initialized_) {
+    auto status = InitializeArchive(archive_);
+    if (!status.ok()) {
+      return status;
+    } else {
```
Comment (schroederc) [inline kythe/cxx/common/kzip_writer.cc]: Remove `else` since the first branch escapes the method?  That's go style.  I'm not sure if it is C++.

File: kythe/cxx/common/kzip_writer.cc [hunk 2]
```diff
@@ -97,6 +118,14 @@ StatusOr<std::string> KzipWriter::WriteUnit(
 }
 
 StatusOr<std::string> KzipWriter::WriteFile(absl::string_view content) {
+  if (!initialized_) {
+    auto status = InitializeArchive(archive_);
+    if (!status.ok()) {
+      return status;
+    } else {
+      initialized_ = true;
```
Comment (schroederc) [inline kythe/cxx/common/kzip_writer.cc]: Same as above.

**Comment by shahms** [comment]
The C++ style guide makes no nevermind over that particular nit ;-)
