### PR TITLE
bazel_go_extractor: Update for current bazel_go rules. 

### LINKED ISSUE #2912: Bazel Go extractor fails trying to load a directory path
Repro:
```
$ bazel build kythe/go/util/schema:schema --experimental_action_listener=//kythe/go/extractors/cmd/bazel:extract_kindex_go --experimental_extra_action_top_level_only
```

Expected: A compilation record.
Observed: 
```
ERROR:$W/kythe/kythe/go/util/schema/BUILD:6:1: Executing extra_action //kythe/go/extractors/cmd/bazel:extra_action on //kythe/go/util/schema:schema failed (Exit 1)
2018/08/09 10:27:29 Extracting XA for "//kythe/go/util/schema:schema" with 11 inputs
2018/08/09 10:27:29 Found 10 required inputs, 0 source files
2018/08/09 10:27:29 Extraction failed: reading input files failed: read bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_stripped/stdlib~/pkg: is a directory
Target //kythe/go/util/schema:schema up-to-date:
  bazel-bin/kythe/go/util/schema/linux_amd64_stripped/schema~/kythe.io/kythe/go/util/schema.a
```

Briefly, the Go rule is advertising the directory containing the standard library, and the extractor is trying to read it. This code hasn't been properly updated since we switched to https://github.com/bazelbuild/rules_go, so it's almost certainly a bug in the extractor.

### PR DESCRIPTION
**Pull request by creachadair**
This program was not updated since we switched away from the legacy Go rules,
and was still expecting the build to generate a symlink forest and other such
nonsense that no longer applies.

Replace that with a much simpler implementation. The action's command line now
includes the file locations directly, so we do not need to guess and remap path
prefixes. Most of the old code was able to be simply deleted.

Fixes #2912.

### CODE REVIEW

File: kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go [hunk 1]
```diff
@@ -32,16 +31,12 @@ import (
...
-	"bitbucket.org/creachadair/stringset"
-
 	apb "kythe.io/kythe/proto/analysis_go_proto"
 	gopb "kythe.io/kythe/proto/go_go_proto"
-	spb "kythe.io/kythe/proto/storage_go_proto"
 )
 
 var (
-	corpus = flag.String("corpus", "kythe", "The corpus label to assign (required)")
+	corpus = flag.String("corpus", "kythe.io", "The corpus label to assign (required)")
```
Comment (schroederc) [inline kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go]: The other extractors use "kythe" as a default.  Can we keep them consistent?

File: kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go [hunk 2]
```diff
@@ -109,352 +106,145 @@ func main() {
...
 	for name, value := range info.Environment {
 		switch name {
 		case "GOOS":
 			e.goos = value
 		case "GOARCH":
 			e.goarch = value
+		case "GOROOT":
+			e.goroot = value
+		case "CGO_ENABLED":
+			e.cgoEnabled = value == "1"
```
Comment (schroederc) [inline kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go]: Does it have to be "1" or can it be any non-empty value?

File: kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go [hunk 3]
```diff
@@ -109,352 +106,145 @@ func main() {
...
 }
 
-func (*extractor) checkEnv(name, _ string) bool {
-	switch name {
-	case "PATH", "GOOS", "GOARCH":
-		return false
+func (e *extractor) checkInput(path string) (string, bool) {
+	switch filepath.Ext(path) {
+	case ".go", ".a":
+		return path, true // keep source files, archives
```
[the remark this answers is not in the document]
Comment (creachadair) [reply kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go]: Right now the indexer can't do anything with them, so no—but if we get to the point where we can handle cgo in the future, we might want those files.

File: kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go (hunk 2 above)
Comment (creachadair) [reply kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go]: I'm not sure. `"1"` is the value the rules use now—and I assume that `"0"` and `""` could probably be taken as false. I didn't actually look at the implementation, though.

File: kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go (hunk 1 above)
Comment (creachadair) [reply kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go]: ✔︎
